---
version: '2.2'
services:
  order:
    build:
      context: ../modules/services/order/orderServiceEar/
    image: novatec/technologyconsulting-showcase-orderdomain:latestlocal
    restart: unless-stopped
    depends_on:
        - kafka1
        - kafka2
        - kafka3
        - schemaregistry1
        - schemaregistry2
    ports:
        - "9080:9080"
        - "9443:9443"
    environment:
      HTTP_PORT: 9080
      HTTPS_PORT: 9443
      MANUFACTURE_WORKORDER_URL: http://manufacture:9090/manufacturedomain/workorder/
      MANUFACTURE_USER: admin
      MANUFACTURE_PASSWORD: adminpwd
      KAFKA_BROKER: kafka:9092
      SCHEMA_REGISTRY: http://schemaregistry:8081
      OAUTH_WITH_SSL: "false"
      OAUTH_LOGIN_SERVER: "keycloak:8080"
      OAUTH_ACCEPT_UNSECURE_SERVER: "true"
      OAUTH_LOGIN_ENDPOINT: "/auth/realms/orderDomain/protocol/openid-connect/token"
      OAUTH_LOGIN_GRANT_TYPE: "client_credentials"
      OAUTH_AUTHORIZATION: "Basic a2Fma2Etb3JkZXItc2VydmljZTo1NDRmMWRjYi1hM2FlLTQ4NGMtYTUyYy0zZjE5YTc3NGExMGI="
