---
version: '2.2'
services:
  inventory:
    build:
      context: ../modules/services/inventory/inventoryService/docker/
    image: novatec/technologyconsulting-showcase-orderdomain-inventoryservice:latestlocal
    restart: unless-stopped
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schemaregistry1
      - schemaregistry2
    environment:
      MANUFACTURE_WORKORDER_URL: http://manufacture:9090/manufacturedomain/workorder/
      MANUFACTURE_USER: admin
      MANUFACTURE_PASSWORD: adminpwd
      KAFKA_BROKER: kafka:9092
      SCHEMA_REGISTRY: http://schemaregistry:8081
      OAUTH_WITH_SSL: "false"
      OAUTH_LOGIN_SERVER: "keycloak:8080"
      OAUTH_ACCEPT_UNSECURE_SERVER: "true"
      OAUTH_LOGIN_ENDPOINT: "/auth/realms/orderDomain/protocol/openid-connect/token"
      OAUTH_LOGIN_GRANT_TYPE: "client_credentials"
      OAUTH_AUTHORIZATION: "Basic a2Fma2EtY2xpZW50OmU5NmFkOThmLTM1YmUtNDY3OS1iYjQ4LTE3NjQzMWRlNjYxYg=="
