---
version: '2.2'
services:
  inventory:
    build:
      context: ../src/inventoryService/docker/
    image: novatec/technologyconsulting-showcase-orderdomain-inventoryservice:latestlocal
    restart: unless-stopped
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schemaregistry1
      - schemaregistry2
    environment:
      MANUFACTURE_WORKORDER_URL: http://manufacture:9090/manufacturedomain/workorder/
      MANUFACTURE_USER: admin
      MANUFACTURE_PASSWORD: adminpwd
      KAFKA_BROKER: kafka:9092
      SCHEMA_REGISTRY: http://schemaregistry:8081
